### ISSUE TITLE
Gravity Forms Cache Buster Breaks Stripe Elements

### ISSUE THREAD

**Issue by TomasHurtz** [gravitywiz/snippet-library#12]
Using Stripe on a gravity form and when using the cache buster, the code breaks the stripe credit card field from appearing.

When deactivating the cache buster, stripe credit card field shows up again

**Comment by spivurno** [comment]
Hi @TomasHurtz, the Issues tab was not intended to be open here. Sorry about that. If you're a [Gravity Perks](https://gravitywiz.com/) customer with an Advanced or Pro license, we'll be happy to help you via our [support form](https://gravitywiz.com/support).
